/*
 * Copyright (c) 2011-2025 Ryan Vogt <rvogt.ca@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include "cprng.h"

#include "common/bytetype.h"
#include "common/errorflow.h"
#include "common/scrub.h"
#include "common/unusedvar.h"

#include <sys/types.h>
#include <sys/uio.h>

#include <fcntl.h>
#include <limits.h>
#include <stddef.h>
#include <stdlib.h>
#include <unistd.h>

/*
 * Whether or not the arc4random() family of functions is available to generate
 * random data. Unless indicated otherwise at compile-time, assume the
 * arc4random() family of functions is available.
 */
#ifndef PISCES_NO_ARC4RANDOM
#define PISCES_NO_ARC4RANDOM (0)
#endif

/*
 * Set the default implementation of the random number generator used by
 * cprng_alloc_default(). If the arc4random() family of functions is available,
 * as indicated at compile-time, use it. Otherwise, use a random-data source
 * from /dev/.
 */
#if PISCES_NO_ARC4RANDOM
#define CPRNG_DEFAULT_ALG (CPRNG_ALG_DEVRANDOM)
#else
#define CPRNG_DEFAULT_ALG (CPRNG_ALG_ARC4RANDOM)
#endif

/*
 * The device name to use if drawing random data from the /dev/ set of devices.
 * It is assumed that reads from the device will eventually succeed; it is a
 * fatal error for a read to fail.
 */
#define CPRNG_DEVICE_NAME ("/dev/random")

/*
 * This struct represents the different cryptographic pseudorandom number
 * generators that can be used.
 */
typedef enum { CPRNG_ALG_ARC4RANDOM, CPRNG_ALG_DEVRANDOM } cprng_algorithm_t;
struct cprng {
    cprng_algorithm_t type;
    int fd;
};

/*
 * Fills the buffer with random data generated by arc4random_buf().
 */
static void cprng_bytes_arc4random(struct cprng *rng, byte_t *bytes,
                                   size_t numBytes);

/*
 * Fills the buffer with random data read from random-soruce device in /dev/
 */
static void cprng_bytes_devrandom(struct cprng *rng, byte_t *bytes,
                                  size_t numBytes);

struct cprng *cprng_alloc_default(void)
{
    struct cprng *ret = (struct cprng *)calloc(1, sizeof(struct cprng));
    GUARD_ALLOC(ret);

    if (PISCES_NO_ARC4RANDOM) {
        ret->type = CPRNG_ALG_DEVRANDOM;
    }
    else {
        ret->type = CPRNG_ALG_ARC4RANDOM;
    }
    ret->fd = -1;

    return ret;
}

void cprng_bytes(struct cprng *rng, byte_t *bytes, size_t numBytes)
{
    ASSERT(numBytes <= SSIZE_MAX, "Amount of data to read is too large");

    switch (rng->type) {
    case CPRNG_ALG_ARC4RANDOM:
        cprng_bytes_arc4random(rng, bytes, numBytes);
        break;
    case CPRNG_ALG_DEVRANDOM:
        cprng_bytes_devrandom(rng, bytes, numBytes);
        break;
    default:
        ASSERT_NEVER_REACH("Invalid CPRNG algorithm");
    }
}

void cprng_free_scrub(struct cprng *rng)
{
    if (rng != NULL) {
        if (rng->fd >= 0) {
            close(rng->fd);
        }
        scrub_memory(rng, sizeof(struct cprng));
        free(rng);
    }
}

static void cprng_bytes_arc4random(struct cprng *rng, byte_t *bytes,
                                   size_t numBytes)
{
#if PISCES_NO_ARC4RANDOM
    UNUSED(rng);
    UNUSED(bytes);
    UNUSED(numBytes);
    ASSERT_NEVER_REACH("Not compiled with arc4random_buf() support");
#else
    UNUSED(rng);
    arc4random_buf(bytes, numBytes);
#endif
}

static void cprng_bytes_devrandom(struct cprng *rng, byte_t *bytes,
                                  size_t numBytes)
{
    ssize_t res;

    if (rng->fd < 0) {
        rng->fd = open(CPRNG_DEVICE_NAME, O_RDONLY);
        if (rng->fd < 0) {
            FATAL_ERROR("Unable to open %s", CPRNG_DEVICE_NAME);
        }
    }

    while (numBytes > 0) {
        res = read(rng->fd, bytes, numBytes);
        if (res == 0) {
            FATAL_ERROR("Read from %s returned no data", CPRNG_DEVICE_NAME);
        }
        if (res < 0) {
            FATAL_ERROR("Read from %s failed", CPRNG_DEVICE_NAME);
        }
        bytes += res;
        numBytes -= (size_t)res;
    }
}
